routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/survey3', 'AdminController@index');
Route::get('/survey2', 'AdminController@newSurvey');

Route::resource('survey', 'NewSurveyController');

Route::get('/', function(){
	return view('surveyHtml');
});



Route::get('/success', function(){
	return view('success');
});

Route::post('getSurvey',  'AdminController@getSurvey')->name('getSurvey');
Route::get('logout', '\App\Http\Controllers\Auth\LoginController@logout');

route::get('/clear/config', function(){
		Artisan::call('config:clear');
	});

route::get('/clear/cache', function(){
	Artisan::call('cache:clear');
});


Auth::routes();
Route::middleware('auth')->prefix('admin')->group(function () {

	Route::get('/',  'AdminReports@index');

	Route::get('/reports',  'AdminReports@index');
	Route::get('/suggestions',  'AdminReports@SuggestionList');

	Route::post('suggestionTable',  'AdminReports@suggestionTable')->name('suggestionTable');

	Route::get('/annual', function(){
		return view('parts.annual');
	});

	Route::post('AnnualReport',  'AdminReports@AnnualReport')->name('AnnualReport');
	Route::post('AnnualExport',  'AdminReports@AnnualExport')->name('AnnualExport');

	Route::get('/comparison', function(){
		return view('parts.comparison');
	});

	Route::resource('questions', 'AdminQuestions');
	Route::resource('categories', 'AdminCategories');
	Route::resource('choices', 'AdminChoices');
	Route::resource('surveys', 'AdminSurvey');
	Route::resource('surveyanswers', 'AdminSurveyAnswer');

	Route::post('chartCount',  'AdminReports@chartCount')->name('chartCount');
	Route::post('chartCountComp',  'AdminComparison@chartCountComp')->name('chartCountComp');
	Route::post('chartPercent',  'AdminReports@chartPercent')->name('chartPercent');
	Route::post('chartComparisonExport',  'AdminComparison@chartComparisonExport')->name('chartComparisonExport');
	Route::post('ActiveCategory',  'AdminCategories@ActiveCategory')->name('ActiveCategory');

	Route::get('/respondents',  'AdminRespondents@index');
	Route::post('getRespondentsDetails',  'AdminRespondents@getRespondentsDetails')->name('getRespondentsDetails');

	Route::post('exportReport',  'AdminReports@exportReport')->name('exportReport');

	route::get('/export', function(){
		return view('parts.export');
	});


});

resources/views/parts/add-category.blade.php
@extends('layouts.app')

@section('content-styles')

    <link rel="stylesheet" href="{{ asset('template/vendor/fontawesome/css/font-awesome.css') }}" />
    <link rel="stylesheet" href="{{ asset('template/vendor/metisMenu/dist/metisMenu.css') }}" />
    <link rel="stylesheet" href="{{ asset('template/vendor/animate.css/animate.css') }}" />
    <link rel="stylesheet" href="{{ asset('template/vendor/bootstrap/dist/css/bootstrap.css') }}" />

    <!-- App styles -->
    <link rel="stylesheet" href="{{ asset('template/vendor/bootstrap-datepicker-master/dist/css/bootstrap-datepicker3.min.css') }}" />
    <link rel="stylesheet" href="{{ asset('template/vendor/eonasdan-bootstrap-datetimepicker/build/css/bootstrap-datetimepicker.min.css') }}" />

    <link rel="stylesheet" href="{{ asset('template/fonts/pe-icon-7-stroke/css/pe-icon-7-stroke.css') }}" />
    <link rel="stylesheet" href="{{ asset('template/fonts/pe-icon-7-stroke/css/helper.css') }}" />
    <link rel="stylesheet" href="{{ asset('template/styles/style.css') }}">

    <style type="text/css">
        .color-line {
            background-color: rgba(128,38,43,0.8) !important;
            background-image: none;
        }
    </style>

@endsection

@section('content')

@include('layouts.header')
<div id="wrapper">

    <div class="content animate-panel">
        @if(session('status'))
        <div class="row">
            <div class="col-lg-12" id="successMessage">
                <div class="hpanel">
                    <div class="panel-body">
                        <div id="" class="alert alert-{{session('status')[0]}}" style="background-color: #dff0d8 !important;color: #3c763d!important; border-color: #d6e9c6 !important;">
                        {{session('status')[1]}}
                        </div>
              
                    </div>
                </div>
            </div>
        </div>
        @endif

        <div class="row">
            <div class="col-lg-12">
                <div class="hpanel">
                    <div class="panel-heading">
                        <div class="panel-tools">
                            <a class="showhide"><i class="fa fa-chevron-up"></i></a>
                        </div>
                        Add Category
                    </div>
                    <div class="panel-body">
                        <form class="form-horizontal" method="POST" action="{{ route('categories.store') }}" >
                        @csrf
                            <div class="form-group"><label class="col-sm-2 control-label">Question Name</label>

                                <div class="col-sm-10">
                                    <div class="col-md-5">
                                        <input type="text" placeholder="" class="form-control" name="category" autocomplete="off">
                                    </div>
                                </div>
                            </div>

                            <div class="form-group"><label class="col-sm-2 control-label">Description</label>

                                <div class="col-sm-10">
                                    <div class="col-md-5">
                                        <textarea class="form-control" name="description" autocomplete="off"></textarea> 
                                    </div>
                                </div>
                            </div>

                            <div class="form-group"><label class="col-sm-2 control-label">Activity Date</label>
                               <div class="col-sm-10">
                                    <div class="col-md-5">
                                        <div class="input-daterange input-group" id="datepicker">
                                            <input type="text" class="input-sm form-control" name="active_from" id="active_from" autocomplete="off">
                                            <span class="input-group-addon">to</span>
                                            <input type="text" class="input-sm form-control" name="active_to" id="active_to" autocomplete="off">
                                        </div>
                                    </div>
                                </div>
                            </div>


                            <div class="hr-line-dashed"></div>
            
                            <div class="form-group">
                                <div class="col-sm-8 col-sm-offset-2">
                                    <a href="{{ route('categories.index') }}" class="btn btn-default">Cancel</a>
                                    <button class="btn btn-primary" type="submit">Save changes</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@include('layouts.footer')
</div>



@endsection


@section('content-scripts')

<script src="{{ asset('template/vendor/jquery/dist/jquery.min.js') }}"></script>
<script src="{{ asset('template/vendor/jquery-ui/jquery-ui.min.js') }}"></script>
<script src="{{ asset('template/vendor/slimScroll/jquery.slimscroll.min.js') }}"></script>
<script src="{{ asset('template/vendor/bootstrap/dist/js/bootstrap.min.js') }}"></script>
<script src="{{ asset('template/vendor/metisMenu/dist/metisMenu.min.js') }}"></script>
<script src="{{ asset('template/vendor/iCheck/icheck.min.js') }}"></script>
<script src="{{ asset('template/vendor/sparkline/index.js') }}"></script>

<script src="{{ asset('template/vendor/moment/moment.js') }}"></script>

<script src="{{ asset('template/vendor/bootstrap-datepicker-master/dist/js/bootstrap-datepicker.min.js') }}"></script>
<script src="{{ asset('template/vendor/eonasdan-bootstrap-datetimepicker/build/js/bootstrap-datetimepicker.min.js') }}"></script>

<!-- App scripts -->
<script src="{{ asset('template/scripts/homer.js') }}"></script>
<script type="text/javascript">
    $(document).ready(function(){
        $('#active_from, #active_to').datepicker();

        setTimeout(function() {
            $('#successMessage').fadeOut('fast');
        }, 5000);
        
    });
</script>
@endsection

resources/views/parts/add-questions.blade.php
@extends('layouts.app')

@section('content-styles')

    <link rel="stylesheet" href="{{ asset('template/vendor/fontawesome/css/font-awesome.css') }}" />
    <link rel="stylesheet" href="{{ asset('template/vendor/metisMenu/dist/metisMenu.css') }}" />
    <link rel="stylesheet" href="{{ asset('template/vendor/animate.css/animate.css') }}" />
    <link rel="stylesheet" href="{{ asset('template/vendor/bootstrap/dist/css/bootstrap.css') }}" />

    <!-- App styles -->
    <link rel="stylesheet" href="{{ asset('template/vendor/bootstrap-datepicker-master/dist/css/bootstrap-datepicker3.min.css') }}" />
    <link rel="stylesheet" href="{{ asset('template/vendor/eonasdan-bootstrap-datetimepicker/build/css/bootstrap-datetimepicker.min.css') }}" />

    <link rel="stylesheet" href="{{ asset('template/fonts/pe-icon-7-stroke/css/pe-icon-7-stroke.css') }}" />
    <link rel="stylesheet" href="{{ asset('template/fonts/pe-icon-7-stroke/css/helper.css') }}" />
    <link rel="stylesheet" href="{{ asset('template/styles/style.css') }}">

    <style type="text/css">
        .color-line {
            background-color: rgba(128,38,43,0.8) !important;
            background-image: none;
        }
    </style>

@endsection

@section('content')

@include('layouts.header')
<div id="wrapper">

    <div class="content animate-panel">
        @if(session('status'))
        <div class="row">
            <div class="col-lg-12" id="successMessage">
                <div class="hpanel">
                    <div class="panel-body">
                        <div id="" class="alert alert-{{session('status')[0]}}" style="background-color: #dff0d8 !important;color: #3c763d!important; border-color: #d6e9c6 !important;">
                        {{session('status')[1]}}
                        </div>
              
                    </div>
                </div>
            </div>
        </div>
        @endif



        <div class="row">
            <div class="col-lg-12">
                <div class="hpanel">
                    <div class="panel-heading">
                        <div class="panel-tools">
                            <a class="showhide"><i class="fa fa-chevron-up"></i></a>
                        </div>
                        Add Questions
                    </div>
                    <div class="panel-body">
                        <form class="form-horizontal" method="POST" action="{{ route('questions.store') }}" >
                        @csrf
                            <div class="form-group"><label class="col-sm-2 control-label">Question Name</label>

                                <div class="col-sm-10">
                                    <div class="col-md-5">
                                        <input type="text" placeholder="" class="form-control" name="question" autocomplete="off">
                                    </div>
                                </div>
                            </div>

                            <div class="form-group"><label class="col-sm-2 control-label">Category</label>
                                <div class="col-sm-10">
                                    <div class="col-md-3">
                                        <select class="form-control m-b" name="category_id">
                                            <option value="">Select</option>
                                            @foreach( $cat as $list )
                                                <option value="{{ $list->id }}">{{ $list->category }}</option>
                                            @endforeach
                                        </select>
                                    </div>
                                </div>
                            </div>


                            <div class="form-group"><label class="col-sm-2 control-label">Description</label>

                                <div class="col-sm-10">
                                    <div class="col-md-5">
                                        <textarea class="form-control" name="description" autocomplete="off"></textarea> 
                                    </div>
                                </div>
                            </div>

                            <div class="form-group"><label class="col-sm-2 control-label">Activity Date</label>
                               <div class="col-sm-10">
                                    <div class="col-md-5">
                                        <div class="input-daterange input-group" id="datepicker">
                                            <input type="text" class="input-sm form-control" name="active_from" id="active_from" autocomplete="off">
                                            <span class="input-group-addon">to</span>
                                            <input type="text" class="input-sm form-control" name="active_to" id="active_to" autocomplete="off">
                                        </div>
                                    </div>
                                </div>
                            </div>


                            <div class="hr-line-dashed"></div>
            
                            <div class="form-group">
                                <div class="col-sm-8 col-sm-offset-2">
                                    <a href="{{ route('categories.index') }}" class="btn btn-default">Cancel</a>
                                    <button class="btn btn-primary" type="submit">Save changes</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@include('layouts.footer')
</div>



@endsection


@section('content-scripts')

<script src="{{ asset('template/vendor/jquery/dist/jquery.min.js') }}"></script>
<script src="{{ asset('template/vendor/jquery-ui/jquery-ui.min.js') }}"></script>
<script src="{{ asset('template/vendor/slimScroll/jquery.slimscroll.min.js') }}"></script>
<script src="{{ asset('template/vendor/bootstrap/dist/js/bootstrap.min.js') }}"></script>
<script src="{{ asset('template/vendor/metisMenu/dist/metisMenu.min.js') }}"></script>
<script src="{{ asset('template/vendor/iCheck/icheck.min.js') }}"></script>
<script src="{{ asset('template/vendor/sparkline/index.js') }}"></script>

<script src="{{ asset('template/vendor/moment/moment.js') }}"></script>

<script src="{{ asset('template/vendor/bootstrap-datepicker-master/dist/js/bootstrap-datepicker.min.js') }}"></script>
<script src="{{ asset('template/vendor/eonasdan-bootstrap-datetimepicker/build/js/bootstrap-datetimepicker.min.js') }}"></script>

<!-- App scripts -->
<script src="{{ asset('template/scripts/homer.js') }}"></script>
<script type="text/javascript">
    $(document).ready(function(){
        $('#active_from, #active_to').datepicker();

        setTimeout(function() {
            $('#successMessage').fadeOut('fast');
        }, 5000);
        
    });
</script>
@endsection

resources/views/parts/categories.blade.php
@extends('layouts.app')

@section('content-styles')

    <link rel="stylesheet" href="{{ asset('template/vendor/fontawesome/css/font-awesome.css') }}" />
    <link rel="stylesheet" href="{{ asset('template/vendor/metisMenu/dist/metisMenu.css') }}" />
    <link rel="stylesheet" href="{{ asset('template/vendor/animate.css/animate.css') }}" />
    <link rel="stylesheet" href="{{ asset('template/vendor/bootstrap/dist/css/bootstrap.css') }}" />

    <!-- App styles -->
    <link rel="stylesheet" href="{{ asset('template/vendor/bootstrap-datepicker-master/dist/css/bootstrap-datepicker3.min.css') }}" />
    <link rel="stylesheet" href="{{ asset('template/vendor/eonasdan-bootstrap-datetimepicker/build/css/bootstrap-datetimepicker.min.css') }}" />

    <link rel="stylesheet" href="{{ asset('template/fonts/pe-icon-7-stroke/css/pe-icon-7-stroke.css') }}" />
    <link rel="stylesheet" href="{{ asset('template/fonts/pe-icon-7-stroke/css/helper.css') }}" />
    <link rel="stylesheet" href="{{ asset('template/styles/style.css') }}">

    <link rel="stylesheet" href="{{ asset('template/vendor/datatables.net-bs/css/dataTables.bootstrap.min.css') }}" />

    <style type="text/css">
        .color-line {
            background-color: rgba(128,38,43,0.8) !important;
            background-image: none;
        }
    </style>

@endsection

@section('content')

@include('layouts.header')
<div id="wrapper">

    <div class="content animate-panel">
        @if(session('status'))
        <div class="row">
            <div class="col-lg-12" id="successMessage">
                <div id="" class="alert alert-{{session('status')[0]}}" style="background-color: #dff0d8 !important;color: #3c763d!important; border-color: #d6e9c6 !important;">
                {{session('status')[1]}}
                </div>
            </div>
        </div>
        @endif
        <div class="row">
            <div class="col-lg-4">
                <div class="hpanel">
                    <div class="panel-heading">
                        <div class="panel-tools">
                            <a class="showhide"><i class="fa fa-chevron-up"></i></a>
                        </div>
                       Actions
                    </div>
                    <div class="panel-body">
                        <div class="form-group">
                            <div class="col-sm-6">
                                <a href="{{ url('/questions') }}" class="btn btn-default" type="submit">Add Questions</a>
                            </div>
                            <div class="col-sm-6">
                                <a href="{{ route('categories.create') }}" class="btn btn-default" type="submit">Add Category</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-lg-12">
               <div class="hpanel">
                    <div class="panel-heading">
                        <div class="panel-tools">
                            <a class="showhide"><i class="fa fa-chevron-up"></i></a>

                        </div>
                        Question Categories
                    </div>
                    <div class="panel-body">
                        <table id="example2" class="table table-striped table-bordered table-hover">
                        <thead>
                        <tr>
                            <th>Category Name</th>
                            <th>Status</th>
                            <th>Active Date</th>
                            <th>Action</th>
                        </tr>
                        </thead>
                            <tbody>
                                @foreach($categories as $list)
                                <tr>
                                    <td>{{ $list->category}}</td>
                                    <td>{{ $list->is_active == '0' ? 'Inactive' : 'Active'}}</td>
                                    <td>
                                        {{ date('Y-m-d',strtotime($list->active_from)) }} 
                                        - 
                                        {{ date('Y-m-d',strtotime($list->active_to)) }} 
                                    </td>
                                    <td>
                                        <form action="{{ route('ActiveCategory') }}" method="post">
                                            @csrf
                                            <input type="hidden" name="category_id" value="{{ $list->id }}">
                                            <button class="btn btn-basic" type="submit">Activate</button>
                                        </form>
                                    </td>
                                </tr>
                                @endforeach  
                            </tbody>
                        </table>

                    </div>
                </div>
            </div>
      
        </div>

    </div>
@include('layouts.footer')
</div>



@endsection


@section('content-scripts')

<script src="{{ asset('template/vendor/jquery/dist/jquery.min.js') }}"></script>
<script src="{{ asset('template/vendor/jquery-ui/jquery-ui.min.js') }}"></script>
<script src="{{ asset('template/vendor/slimScroll/jquery.slimscroll.min.js') }}"></script>
<script src="{{ asset('template/vendor/bootstrap/dist/js/bootstrap.min.js') }}"></script>
<script src="{{ asset('template/vendor/metisMenu/dist/metisMenu.min.js') }}"></script>
<script src="{{ asset('template/vendor/iCheck/icheck.min.js') }}"></script>
<script src="{{ asset('template/vendor/sparkline/index.js') }}"></script>

<!-- DataTables -->
<script src="{{ asset('template/vendor/datatables/media/js/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('template/vendor/datatables.net-bs/js/dataTables.bootstrap.min.js') }}"></script>
<!-- DataTables buttons scripts -->
<script src="{{ asset('template/vendor/pdfmake/build/pdfmake.min.js') }}"></script>
<script src="{{ asset('template/vendor/pdfmake/build/vfs_fonts.js') }}"></script>
<script src="{{ asset('template/vendor/datatables.net-buttons/js/buttons.html5.min.js') }}"></script>
<script src="{{ asset('template/vendor/datatables.net-buttons/js/buttons.print.min.js') }}"></script>
<script src="{{ asset('template/vendor/datatables.net-buttons/js/dataTables.buttons.min.js') }}"></script>
<script src="{{ asset('template/vendor/datatables.net-buttons-bs/js/buttons.bootstrap.min.js') }}"></script>

<script src="{{ asset('template/vendor/moment/moment.js') }}"></script>

<script src="{{ asset('template/vendor/bootstrap-datepicker-master/dist/js/bootstrap-datepicker.min.js') }}"></script>
<script src="{{ asset('template/vendor/eonasdan-bootstrap-datetimepicker/build/js/bootstrap-datetimepicker.min.js') }}"></script>



<!-- App scripts -->
<script src="{{ asset('template/scripts/homer.js') }}"></script>
<script type="text/javascript">
    $(document).ready(function(){
        $('#example2').dataTable();
        $('#active_from, #active_to').datepicker();

        setTimeout(function() {
            $('#successMessage').fadeOut('fast');
        }, 5000);
        
    });
</script>
@endsection

resources/views/parts/choices.blade.php
@extends('layouts.app')

@section('content-styles')

    <link rel="stylesheet" href="{{ asset('template/vendor/fontawesome/css/font-awesome.css') }}" />
    <link rel="stylesheet" href="{{ asset('template/vendor/metisMenu/dist/metisMenu.css') }}" />
    <link rel="stylesheet" href="{{ asset('template/vendor/animate.css/animate.css') }}" />
    <link rel="stylesheet" href="{{ asset('template/vendor/bootstrap/dist/css/bootstrap.css') }}" />

    <!-- App styles -->
    <link rel="stylesheet" href="{{ asset('template/vendor/bootstrap-datepicker-master/dist/css/bootstrap-datepicker3.min.css') }}" />
    <link rel="stylesheet" href="{{ asset('template/vendor/eonasdan-bootstrap-datetimepicker/build/css/bootstrap-datetimepicker.min.css') }}" />

    <link rel="stylesheet" href="{{ asset('template/fonts/pe-icon-7-stroke/css/pe-icon-7-stroke.css') }}" />
    <link rel="stylesheet" href="{{ asset('template/fonts/pe-icon-7-stroke/css/helper.css') }}" />
    <link rel="stylesheet" href="{{ asset('template/styles/style.css') }}">

    <style type="text/css">
        .color-line {
            background-color: rgba(128,38,43,0.8) !important;
            background-image: none;
        }
    </style>

@endsection

@section('content')

@include('layouts.header')
<div id="wrapper">

    <div class="content animate-panel">
        @if(session('status'))
        <div class="col-lg-12" id="successMessage" >
                <div class="hpanel">
                    <div class="panel-body">
                      
                        <div class="alert alert-{{session('status')[0]}}" style="background-color: #dff0d8 !important;color: #3c763d!important; border-color: #d6e9c6 !important;">
                        {{session('status')[1]}}
                        </div>
              
                    </div>
                </div>
            </div>
        @endif



        <div class="row">
            <div class="col-lg-12">
                <div class="hpanel">
                    <div class="panel-heading">
                        <div class="panel-tools">
                            <a class="showhide"><i class="fa fa-chevron-up"></i></a>
                        </div>
                        Add Choices
                    </div>
                    <div class="panel-body">
                        <form class="form-horizontal" method="POST" action="{{ route('choices.store') }}" >
                        @csrf
                            <div class="form-group"><label class="col-sm-2 control-label">Question Name</label>
                                <div class="col-sm-10">
                                    <div class="col-md-5">
                                        <select class="form-control m-b" name="question_id">
                                            <option>Select</option>
                                            @foreach($questions as $question)
                                                <option value="{{$question->id}}">{{$question->question}}</option>
                                            @endforeach
                                        </select>
                                    </div>
                                </div>
                            </div>

                            <div class="form-group"><label class="col-sm-2 control-label">Choice Name #1</label>

                                <div class="col-sm-10">
                                    <div class="col-md-4">
                                        <input type="text" placeholder="" class="form-control" name="choice1">
                                    </div>
                                </div>
                            </div>

                            <div class="form-group"><label class="col-sm-2 control-label">Choice Name #2</label>

                                <div class="col-sm-10">
                                    <div class="col-md-4">
                                        <input type="text" placeholder="" class="form-control" name="choice2">
                                    </div>
                                </div>
                            </div>

                            <div class="form-group"><label class="col-sm-2 control-label">Choice Name #3</label>

                                <div class="col-sm-10">
                                    <div class="col-md-4">
                                        <input type="text" placeholder="" class="form-control" name="choice3">
                                    </div>
                                </div>
                            </div>

                            <div class="form-group"><label class="col-sm-2 control-label">Choice Name #4</label>

                                <div class="col-sm-10">
                                    <div class="col-md-4">
                                        <input type="text" placeholder="" class="form-control" name="choice4">
                                    </div>
                                </div>
                            </div>

                            <div class="form-group"><label class="col-sm-2 control-label">Choice Name #5</label>

                                <div class="col-sm-10">
                                    <div class="col-md-4">
                                        <input type="text" placeholder="" class="form-control" name="choice5">
                                    </div>
                                </div>
                            </div>

                            <div class="hr-line-dashed"></div>
            
                            <div class="form-group">
                                <div class="col-sm-8 col-sm-offset-2">
                                    <a href="{{ route('choices.index') }}" class="btn btn-default">Cancel</a>
                                    <button class="btn btn-primary" type="submit">Save changes</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@include('layouts.footer')
</div>



@endsection


@section('content-scripts')

<script src="{{ asset('template/vendor/jquery/dist/jquery.min.js') }}"></script>
<script src="{{ asset('template/vendor/jquery-ui/jquery-ui.min.js') }}"></script>
<script src="{{ asset('template/vendor/slimScroll/jquery.slimscroll.min.js') }}"></script>
<script src="{{ asset('template/vendor/bootstrap/dist/js/bootstrap.min.js') }}"></script>
<script src="{{ asset('template/vendor/metisMenu/dist/metisMenu.min.js') }}"></script>
<script src="{{ asset('template/vendor/iCheck/icheck.min.js') }}"></script>
<script src="{{ asset('template/vendor/sparkline/index.js') }}"></script>

<script src="{{ asset('template/vendor/moment/moment.js') }}"></script>

<script src="{{ asset('template/vendor/bootstrap-datepicker-master/dist/js/bootstrap-datepicker.min.js') }}"></script>
<script src="{{ asset('template/vendor/eonasdan-bootstrap-datetimepicker/build/js/bootstrap-datetimepicker.min.js') }}"></script>

<!-- App scripts -->
<script src="{{ asset('template/scripts/homer.js') }}"></script>
<script type="text/javascript">
    $(document).ready(function(){
        $('#active_from, #active_to').datepicker();

        setTimeout(function() {
            $('#successMessage').fadeOut('fast');
        }, 5000);
        
    });
</script>
@endsection